on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  install-deps:
    if: github.repository == 'teknologi-pendidikan/pameran-karya'
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"
          cache: 'pnpm'

      - name: Install locked dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    if: github.repository == 'teknologi-pendidikan/pameran-karya'
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"
          cache: 'pnpm'

      - name: Lint files
        run: pnpm run lint

  type-check:
    if: github.repository == 'teknologi-pendidikan/pameran-karya'
    name: Type check
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"
          cache: 'pnpm'

      - name: Perform type checking
        run: pnpm run tsc

#   test:
#     name: Unit and integration tests
#     runs-on: ubuntu-latest
#     needs: install-deps
#     steps:
#       - name: Restore cached dependencies
#         uses: actions/cache@v1
#         id: restore-deps
#         with:
#           path: "."
#           key: ${{ github.sha }}

#       - name: Setup Node.js 16.x
#         uses: actions/setup-node@v3.6.0
#         with:
#           node-version: "16.x"
#           cache: 'pnpm'

#       - name: Run Jest
#         run: pnpm run test
#         env:
#           CI: true

#       - name: Upload code coverage reports to Codecov
#         uses: codecov/codecov-action@v2
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}

#   e2e:
#     name: End-to-end tests
#     runs-on: ubuntu-latest
#     needs: install-deps
#     steps:
#       - name: Restore cached dependencies
#         uses: actions/cache@v1
#         id: restore-deps
#         with:
#           path: "."
#           key: ${{ github.sha }}

#       - name: Setup Node.js 16.x
#         uses: actions/setup-node@v3.6.0
#         with:
#           node-version: "16.x"
#           cache: 'pnpm'

#       - name: Install Cypress
#         run: pnpm add install

#       - name: Run Cypress
#         uses: cypress-io/github-action@v2
#         with:
#           record: true
#           start: yarn dev
#           wait-on: "http://localhost:3000"
#         env:
#           CI: true
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
